apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: developer-sandbox-ui
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: developer-sandbox-ui
    app.kubernetes.io/part-of: developer-sandbox-ui
  name: developer-sandbox-ui
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: developer-sandbox-ui
status:
  loadBalancer: {}
